Vagrant.configure("2") do |config|

    config.vm.provider "docker" do |d|
        d.build_dir = "."
        d.volumes = ["/vagrant:/data"]
        d.remains_running = false
        d.vagrant_vagrantfile = "../Vagrantfile"
    end

end
